    Soo = So; So = S;
    Coo = Co; Co = C;
    Xoo = Xo; Xo = X;
    Foo = Fo; Fo = F;
    Moo = Mo; Mo = M;
    rhooo = rhoo; rhoo = rho;
    TRCoo = TRCo; TRCo = TRC;
    dSdtoo = dSdto; dSdto = dSdt;
    dCdtoo = dCdto; dCdto = dCdt;
    dXdtoo = dXdto; dXdto = dXdt;
    dFdtoo = dFdto; dFdto = dFdt;
    dMdtoo = dMdto; dMdto = dMdt;
    drhodtoo = drhodto; drhodto = drhodt;
    dTRCdtoo = dTRCdto; dTRCdto = dTRCdt;
    Div_Vo  = Div_V;
    rhoWoo  = rhoWo; rhoWo = rhofz.*W(:,2:end-1);
    rhoUoo  = rhoUo; rhoUo = rhofx.*U(2:end-1,:);
    Pchmboo = Pchmbo; Pchmbo = Pchmb;
    dPchmbdtoo = dPchmbdto; dPchmbdto = dPchmbdt;
    Pto     = Pt;
    Tpoo    = Tpo;  Tpo = Tp;
    Too     = To;   To  = T;
    dTpdtoo = dTpdto; dTpdto = dTpdt;
    dTdtoo  = dTdto;  dTdto  = dTdt;
    so      = s;
    dto     = dt;